composer:
  name: octolab/cleaner
  type: plugin
  description:
  homepage: https://github.com/octolab/Cleaner
  license: MIT

  authors:
  - name: Kamil Samigullin
    email: kamil@samigullin.info
    role: lead

  require:
    php: ^5.3.2 || ^7.0
    # it's provides to project
    # - symfony/finder
    # - symfony/filesystem
    composer/composer: ~1.1
